# docker compose -f deploy/docker-compose.yml up -d
services:
  ameisennav:
    build: ..
    image: ameisennav
    restart: unless-stopped
    ports:
      - "47110:47110"
    volumes:
      - ./meshes:/meshes:ro
    environment:
      ANAV_bUseAnpFileFormat: "1"
      ANAV_sPreloadMaps: "0,1,530,571"
